name: Build Pocket

on:
    workflow_dispatch:
        inputs:
            version_prefix:
                description: 'Version prefix (e.g. 1.0.0, 1.1.0, 2.0.0)'
                required: true
                default: '2.0.0'
            
            prerelease:
                description: 'Mark as pre-release'
                required: true
                default: 'true'
                type: choice
                options:
                    - 'true'
                    - 'false'

jobs:
    patch:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        outputs:
            VERSION: ${{ steps.version.outputs.VERSION }}
            VERSION_NUMBER: ${{ steps.version.outputs.VERSION_NUMBER }}
        steps:
            -   name: Checkout
                uses: actions/checkout@v7
            
            -   name: Checkout custom
                uses: actions/checkout@v7
                with:
                    repository: anthony-hyo/pocket-patches
                    token: ${{ secrets.PATCHES_TOKEN }}
                    path: pocket-patches
            
            -   name: Set version
                id: version
                run: |
                    echo "VERSION=v${{ github.event.inputs.version_prefix }}" >> $GITHUB_OUTPUT
                    echo "VERSION_NUMBER=${{ github.event.inputs.version_prefix }}" >> $GITHUB_OUTPUT
                    echo "IS_PRERELEASE=${{ github.event.inputs.prerelease }}" >> $GITHUB_OUTPUT
            
            -   name: Setup Rust
                uses: dtolnay/rust-toolchain@stable
            
            -   name: Cache Rust dependencies
                uses: actions/cache@v6
                with:
                    path: |
                        ~/.cargo/registry
                        ~/.cargo/git
                        target
                    key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            
            -   name: Setup Dlang
                uses: dlang-community/setup-dlang@v1
            
            -   name: Install Dependencies and Build RABCDAsm
                run: |
                    sudo apt-get update
                    sudo apt-get install -y wget unzip git curl liblzma-dev default-jdk
                    
                    git clone --depth 1 https://github.com/CyberShadow/RABCDAsm.git
                    cd RABCDAsm
                    dmd -run build_rabcdasm.d
                    sudo cp abcexport rabcdasm rabcasm abcreplace /usr/local/bin/
            
            -   name: Patch Game.swf
                run: cargo run --release
            
            -   name: Keystore
                run: |
                    echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > aqwpocket_keystore.jks
                    echo "${{ secrets.KEYSTORE_P12_BASE64 }}" | base64 -d > aqwpocket_keystore.p12
            
            -   name: Inject version
                run: |
                    sed -i "s|<versionNumber>.*</versionNumber>|<versionNumber>${{ steps.version.outputs.VERSION_NUMBER }}</versionNumber>|" loader/Mobile-app.xml
                    sed -i "s|<versionLabel>.*</versionLabel>|<versionLabel>${{ steps.version.outputs.VERSION_NUMBER }}</versionLabel>|" loader/Mobile-app.xml
                    sed -i "s|<versionNumber>.*</versionNumber>|<versionNumber>${{ steps.version.outputs.VERSION_NUMBER }}</versionNumber>|" loader/Desktop-app.xml
                    sed -i "s|<versionLabel>.*</versionLabel>|<versionLabel>${{ steps.version.outputs.VERSION_NUMBER }}</versionLabel>|" loader/Desktop-app.xml
            
            -   name: Upload patched files
                uses: actions/upload-artifact@v7
                with:
                    name: patched-files
                    path: |
                        loader/
                        aqwpocket_keystore.jks
                        aqwpocket_keystore.p12
    
    build-android:
        needs: patch
        runs-on: ubuntu-latest
        permissions:
            contents: write
        strategy:
            matrix:
                include:
                    -   architecture: "armv8"
                        render-mode: "auto"
                        suffix: ""
                    
                    -   architecture: "armv8"
                        render-mode: "direct"
                        suffix: "-direct"
                    
                    -   architecture: "armv8"
                        render-mode: "gpu"
                        suffix: "-gpu"
                    
                    -   architecture: "armv7"
                        render-mode: "auto"
                        suffix: ""
                    
                    -   architecture: "x64"
                        render-mode: "auto"
                        suffix: ""
                    
                    -   architecture: "x86"
                        render-mode: "auto"
                        suffix: ""
        
        steps:
            -   name: Download patched files
                uses: actions/download-artifact@v8
                with:
                    name: patched-files
            
            -   name: Setup AIR SDK
                uses: joshtynjala/setup-adobe-air-action@v2
                with:
                    air-version: "51.3.1"
                    accept-license: yes   
            -    name: Compile modified Mobile.swf
                 run: |
                  mxmlc \
                      -source-path+=loader/src \
                      -library-path+=loader/libs \
                      -output=loader/Mobile.swf \
                      loader/src/Pocket.as
            -   name: Build APK
                run: |
                    sed -i "s|<renderMode>.*</renderMode>|<renderMode>${{ matrix.render-mode }}</renderMode>|" loader/Mobile-app.xml
                    adt -package \
                      -target apk-captive-runtime \
                      -arch ${{ matrix.architecture }} \
                      -storetype JKS \
                      -keystore aqwpocket_keystore.jks \
                      -storepass ${{ secrets.KEYSTORE_PASS }} \
                      -keypass ${{ secrets.KEY_PASS }} \
                      AQWPocket-${{ needs.patch.outputs.VERSION }}-${{ matrix.architecture }}${{ matrix.suffix }}.apk \
                      loader/Mobile-app.xml \
                      -C loader \
                        Mobile.swf \
                        icons/icon-36x36.png \
                        icons/icon-48x48.png \
                        icons/icon-72x72.png \
                        icons/icon-96x96.png \
                        icons/icon-144x144.png \
                        icons/icon-192x192.png \
                        gamefiles/game.swf \
                        gamefiles/world-map.swf \
                        gamefiles/book-of-lore.swf \
                        gamefiles/character-select.swf
            
            -   name: Upload
                uses: actions/upload-artifact@v7
                with:
                    name: build-${{ matrix.architecture }}${{ matrix.suffix }}
                    path: "*.apk"

    build-windows:
        needs: patch
        runs-on: windows-latest
        permissions:
            contents: write
        strategy:
            matrix:
                include:
                    -   architecture: "x64"
                        render-mode: "auto"
                        suffix: "-windows-x64"

                    -   architecture: "x64"
                        render-mode: "direct"
                        suffix: "-windows-x64-direct"

                    -   architecture: "x86"
                        render-mode: "auto"
                        suffix: "-windows-x86"
        steps:
            -   name: Download patched files
                uses: actions/download-artifact@v8
                with:
                    name: patched-files

            -   name: Setup AIR SDK
                uses: joshtynjala/setup-adobe-air-action@v2
                with:
                    air-version: "51.3.1"
                    accept-license: yes

            -   name: Build Windows
                run: |
                    (Get-Content loader/Desktop-app.xml) `
                      -replace '<renderMode>.*</renderMode>', '<renderMode>${{ matrix.render-mode }}</renderMode>' `
                      | Set-Content loader/Desktop-app.xml
                    adt -package `
                      -storetype PKCS12 `
                      -keystore aqwpocket_keystore.p12 `
                      -storepass ${{ secrets.KEYSTORE_PASS }} `
                      -keypass ${{ secrets.KEY_PASS }} `
                      -target bundle `
                      -arch ${{ matrix.architecture }} `
                      AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }} `
                      loader/Desktop-app.xml `
                      -extdir loader/libs `
                      -C loader `
                        Desktop.swf `
                        icons/icon-16x16.png `
                        icons/icon-32x32.png `
                        icons/icon-36x36.png `
                        icons/icon-48x48.png `
                        icons/icon-72x72.png `
                        icons/icon-96x96.png `
                        icons/icon-128x128.png `
                        icons/icon-144x144.png `
                        icons/icon-192x192.png `
                        gamefiles/game.swf `
                        gamefiles/world-map.swf `
                        gamefiles/book-of-lore.swf `
                        gamefiles/character-select.swf

            -   name: Zip
                run: Compress-Archive -Path "AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }}" -DestinationPath "AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }}.zip"

            -   name: Upload
                uses: actions/upload-artifact@v7
                with:
                    name: build${{ matrix.suffix }}
                    path: "AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }}.zip"

    build-macos:
        needs: patch
        runs-on: macos-latest
        permissions:
            contents: write
        strategy:
            matrix:
                include:
                    -   architecture: "x64"
                        render-mode: "auto"
                        suffix: "-macos-x64"
                    -   architecture: "x64"
                        render-mode: "direct"
                        suffix: "-macos-x64-direct"
        steps:
            -   name: Download patched files
                uses: actions/download-artifact@v8
                with:
                    name: patched-files

            -   name: Setup AIR SDK
                uses: joshtynjala/setup-adobe-air-action@v2
                with:
                    air-version: "51.3.1"
                    accept-license: yes

            -   name: Build macOS
                run: |
                    sed -i '' "s|<renderMode>.*</renderMode>|<renderMode>${{ matrix.render-mode }}</renderMode>|" loader/Desktop-app.xml
                    adt -package \
                      -storetype PKCS12 \
                      -keystore aqwpocket_keystore.p12 \
                      -storepass ${{ secrets.KEYSTORE_PASS }} \
                      -keypass ${{ secrets.KEY_PASS }} \
                      -target bundle \
                      -arch ${{ matrix.architecture }} \
                      AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }} \
                      loader/Desktop-app.xml \
                      -extdir loader/libs \
                      -C loader \
                        Desktop.swf \
                        icons/icon-16x16.png \
                        icons/icon-32x32.png \
                        icons/icon-36x36.png \
                        icons/icon-48x48.png \
                        icons/icon-72x72.png \
                        icons/icon-96x96.png \
                        icons/icon-128x128.png \
                        icons/icon-144x144.png \
                        icons/icon-192x192.png \
                        gamefiles/game.swf \
                        gamefiles/world-map.swf \
                        gamefiles/book-of-lore.swf \
                        gamefiles/character-select.swf

            -   name: Zip
                run: zip -r AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }}.zip AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }}/

            -   name: Upload
                uses: actions/upload-artifact@v7
                with:
                    name: build${{ matrix.suffix }}
                    path: "AQWPocket-${{ needs.patch.outputs.VERSION }}${{ matrix.suffix }}.zip"

    publish:
        needs: [patch, build-android, build-windows, build-macos]
        runs-on: ubuntu-latest
        permissions:
            contents: write
        
        steps:
            -   name: Checkout
                uses: actions/checkout@v7
                
            -   name: Download builds
                uses: actions/download-artifact@v7
                with:
                    pattern: build-*
                    merge-multiple: true
            
            -   name: Release
                uses: softprops/action-gh-release@v2
                with:
                    tag_name: ${{ needs.patch.outputs.VERSION }}
                    name: ${{ needs.patch.outputs.VERSION }}${{ github.event.inputs.prerelease == 'true' && ' (test)' || '' }}
                    prerelease: ${{ github.event.inputs.prerelease }}
                    body: |
                        ## Which file should I download?

                        ### Android

                        * **armv8 (recommended)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-armv8.apk`
                        → For most modern devices

                        * **armv8-direct (alternative)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-armv8-direct.apk`
                        → Use if the recommended version has issues

                        * **armv8-gpu (legacy)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-armv8-gpu.apk`
                        → Not recommended; fallback only

                        * **armv7 (32-bit)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-armv7.apk`
                        → For older devices only

                        ---

                        ### ChromeOS

                        * `AQWPocket-${{ needs.patch.outputs.VERSION }}-x86.apk`
                        * `AQWPocket-${{ needs.patch.outputs.VERSION }}-x64.apk`

                        ---

                        ### Windows

                        * **x64 (recommended)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-windows-x64.zip`

                        * **x64-direct (alternative)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-windows-x64-direct.zip`

                        * **x86 (older systems)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-windows-x86.zip`

                        ---

                        ### macOS

                        * **x64 (recommended)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-macos-x64.zip`

                        * **x64-direct (alternative)**
                        `AQWPocket-${{ needs.patch.outputs.VERSION }}-macos-x64-direct.zip`
                    files: |
                        *.apk
                        *.zip
